project_name: gitignore

env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io

before:
  hooks:
    - go mod download

builds:
- binary: gitignore
  env:
    - CGO_ENABLED=0

  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=wesleimp

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
- image_templates:
    - 'wesleimp/gitignore:latest'
    - 'wesleimp/gitignore:{{ .Tag }}'
  dockerfile: Dockerfile
  binaries:
    - gitignore
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=repository=http://github.com/wesleimp/gitignore"
    - "--label=homepage=http://github.com/wesleimp/gitignore"
    - "--label=maintainer=Weslei Juan Moser Pereira <wesleimsr@gmail.com>"
  extra_files:
    - scripts/entrypoint.sh

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip